spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intensive-team-db
    username: postgres
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: false

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher

  web:
    resources:
      add-mappings: false
